CREATE TYPE lockerhub.office AS ENUM (
    '15 Canada Square',
    'Malta',
    'Nottingham',
    'Watford',
    'Birmingham',
    'Leeds',
    'Reading',
    'Manchester',
    'Liverpool',
    'Glasgow 319',
    'Bristol Queen Square',
    'Edinburgh',
    'Newcastle upon Tyne',
    'South Coast - Southampton',
    'Gibraltar',
    'Gatwick',
    'Canada Square IFRG',
    'Cambridge',
    'Cardiff',
    'Milton Keynes',
    'Aberdeen',
    '15 Canada Square EMA',
    'Plymouth',
    'Overseas',
    'Zurich',
    'Glasgow Tax CoE',
    'Bangalore (KGS)',
    'New Delhi (KRC)',
    'Spain'
);
